application:
  secret: "4a1a170137d3f75876313a558f29fe9b"
  port: 8001 # port server

warehouseservice:
  db:
    lists: "user=postgres password=secrect host=localhost port=5432 dbname=warehouse sslmode=disable TimeZone=Asia/Jakarta"
    name: "user"
    migrations: 
      connstrings: "postgres://postgres:secrect@localhost:5432/warehouse?sslmode=disable"
      folder: "file://migrations"

cors:
  whitelist: "*"

client:
  user:
    host: http://localhost:8000
    checktoken: /validate-token
  warehouse:
    host: http://localhost:8001
    checktoken: /validate-token