application:
  secret: "4a1a170137d3f75876313a558f29fe9b"
  port: 8004 # port server

productservice:
  db:
    lists: "user=postgres password=secrect host=localhost port=5432 dbname=product sslmode=disable TimeZone=Asia/Jakarta"
    name: "user"
    migrations: 
      connstrings: "postgres://postgres:secrect@localhost:5432/product?sslmode=disable"
      folder: "file://migrations"

cors:
  whitelist: "*"

client:
  user:
    host: http://localhost:8000
    checktoken: /validate-token
  warehouse:
    host: http://localhost:8001
    stockproduct: /warehouse/stock